<<<<<<< HEAD
// types.js

export const ACTUALIZAR_EVENTOS = 'ACTUALIZAR_EVENTOS';
export const AGREGAR_EVENTO = 'AGREGAR_EVENTO';
export const ELIMINAR_EVENTO = 'ELIMINAR_EVENTO';
// Agrega más constantes de tipo según tus necesidades
// types.js
export const ACTUALIZAR_EVENTO_SELECCIONADO = 'ACTUALIZAR_EVENTO_SELECCIONADO';
=======

export const eventsTypes = {
 OBTENER_EVENTOS: 'OBTENER_EVENTOS',
 AGREGAR_EVENTO: 'AGREGAR_EVENTO',
 ELIMINAR_EVENTO: 'ELIMINAR_EVENTO',
 ACTUALIZAR_EVENTO: 'ACTUALIZAR_EVENTO'
}

export const adminTypes = {
 OBTENER_ADMINISTRADORES: 'OBTENER_ADMINISTRADORES',
 AGREGAR_ADMINISTRADOR: 'AGREGAR_ADMINISTRADOR',
 ELIMINAR_ADMINISTRADOR: 'ELIMINAR_ADMINISTRADOR',
 ACTUALIZAR_ADMINISTRADOR: 'ACTUALIZAR_ADMINISTRADOR'
}
>>>>>>> origin/develop
