
export const eventsTypes = {
 OBTENER_EVENTOS: 'OBTENER_EVENTOS',
 AGREGAR_EVENTO: 'AGREGAR_EVENTO',
 ELIMINAR_EVENTO: 'ELIMINAR_EVENTO',
 ACTUALIZAR_EVENTO: 'ACTUALIZAR_EVENTO'
}

export const adminTypes = {
 OBTENER_ADMINISTRADORES: 'OBTENER_ADMINISTRADORES',
 AGREGAR_ADMINISTRADOR: 'AGREGAR_ADMINISTRADOR',
 ELIMINAR_ADMINISTRADOR: 'ELIMINAR_ADMINISTRADOR',
 ACTUALIZAR_ADMINISTRADOR: 'ACTUALIZAR_ADMINISTRADOR'
}
// types.js

export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
